### ISSUE TITLE
Please consider re-licensing this repository

### ISSUE THREAD

**Issue by arfon** [idris-hackers/idris-sublime#5]
Hello there, we'd love to use this library to syntax-highlight files on GitHub but in order to do so we need this library to have a more permissive license.

If you don't have any particular reason for choosing GPL would you be willing to consider switching this to a more permissive license such as MIT, BSD or Apache 2?

Many thanks
Arfon (GitHub Staff)

**Comment by melted** [comment]
I'm fine with any license, what I did was from before GPL3 got put on it anyway.

Hey @laughedelic, @LeifW, is that ok with you?

**Comment by laughedelic** [comment]
I'm fine with it :+1:

**Comment by copumpkin** [comment]
Idris was removed from the standard set of highlighters on GitHub as a result of this: https://github.com/github/linguist/pull/2884

**Comment by LeifW** [comment]
I'm fine with whatever license. MIT?

**Comment by LeifW** [comment]
GitHub uses TextMate or Sublime highlighters? Last I heard it was pygments.

**Comment by arfon** [comment]
:+1: many thanks. This is now merged into Linguist (https://github.com/github/linguist/issues/2936) and should be live later this week.
